import type { ExerciseDefinition } from './trainingTypes'

interface StandardExerciseInput {
  id: string
  name: string
  primaryMuscles: string[]
  secondaryMuscles?: string[]
  equipment: string[]
  unit?: ExerciseDefinition['unit']
  description: string
  gripOptions?: string[]
  supportsBodyweightModes?: boolean
}

function defineStandardExercise({
  id,
  name,
  primaryMuscles,
  secondaryMuscles = [],
  equipment,
  unit = 'kg-reps',
  description,
  gripOptions = [],
  supportsBodyweightModes = false,
}: StandardExerciseInput): ExerciseDefinition {
  return {
    id,
    source: 'standard',
    name,
    primaryMuscles,
    secondaryMuscles,
    equipment,
    unit,
    description,
    gripOptions,
    supportsBodyweightModes,
    illustrationPath: `training/exercises/${id}.svg`,
  }
}

export const STANDARD_EXERCISES: readonly ExerciseDefinition[] = [
  defineStandardExercise({
    id: 'bench-press',
    name: 'Bankdrücken',
    primaryMuscles: ['Brust'],
    secondaryMuscles: ['Trizeps', 'Vordere Schulter'],
    equipment: ['Langhantel', 'Flachbank'],
    description: 'Langhantel kontrolliert zur Brust senken und über der Schulterlinie auspressen.',
  }),
  defineStandardExercise({
    id: 'incline-bench-press',
    name: 'Schrägbankdrücken',
    primaryMuscles: ['Obere Brust'],
    secondaryMuscles: ['Trizeps', 'Vordere Schulter'],
    equipment: ['Langhantel', 'Schrägbank'],
    description: 'Auf der Schrägbank zur oberen Brust absenken und stabil nach oben drücken.',
  }),
  defineStandardExercise({
    id: 'dumbbell-bench-press',
    name: 'Kurzhantel-Bankdrücken',
    primaryMuscles: ['Brust'],
    secondaryMuscles: ['Trizeps', 'Vordere Schulter'],
    equipment: ['Kurzhanteln', 'Flachbank'],
    description: 'Kurzhanteln seitlich zur Brust führen und gleichmäßig über dem Oberkörper drücken.',
  }),
  defineStandardExercise({
    id: 'incline-dumbbell-press',
    name: 'Kurzhantel-Schrägbankdrücken',
    primaryMuscles: ['Obere Brust'],
    secondaryMuscles: ['Trizeps', 'Vordere Schulter'],
    equipment: ['Kurzhanteln', 'Schrägbank'],
    description: 'Kurzhanteln auf der Schrägbank aus einer tiefen Ellbogenposition nach oben drücken.',
  }),
  defineStandardExercise({
    id: 'machine-chest-press',
    name: 'Brustpresse',
    primaryMuscles: ['Brust'],
    secondaryMuscles: ['Trizeps', 'Vordere Schulter'],
    equipment: ['Brustpresse'],
    description: 'Griffe aus der Brusthöhe nach vorn drücken und kontrolliert zurückführen.',
  }),
  defineStandardExercise({
    id: 'pec-deck',
    name: 'Butterfly an der Pec-Deck-Maschine',
    primaryMuscles: ['Brust'],
    secondaryMuscles: ['Vordere Schulter'],
    equipment: ['Pec-Deck-Maschine'],
    description: 'Unterarme an den Polstern anlegen und die Arme vor der Brust zusammenführen.',
  }),
  defineStandardExercise({
    id: 'cable-fly',
    name: 'Kabel-Flys',
    primaryMuscles: ['Brust'],
    secondaryMuscles: ['Vordere Schulter'],
    equipment: ['Kabelzug', 'Einhandgriffe'],
    description: 'Die leicht gebeugten Arme aus breiter Position bogenförmig vor der Brust schließen.',
  }),
  defineStandardExercise({
    id: 'lat-pulldown',
    name: 'Latziehen zur Brust',
    primaryMuscles: ['Latissimus'],
    secondaryMuscles: ['Bizeps', 'Hintere Schulter'],
    equipment: ['Latzug', 'Latzugstange'],
    description: 'Die Stange aus gestreckten Armen kontrolliert zur oberen Brust ziehen.',
    gripOptions: ['Breit', 'Eng', 'Neutral', 'Untergriff'],
  }),
  defineStandardExercise({
    id: 'close-grip-lat-pulldown',
    name: 'Latziehen mit engem Griff',
    primaryMuscles: ['Latissimus'],
    secondaryMuscles: ['Bizeps', 'Mittlerer Rücken'],
    equipment: ['Latzug', 'Parallelgriff'],
    description: 'Den engen Griff zur Brust ziehen und die Schulterblätter nach unten führen.',
    gripOptions: ['Breit', 'Eng', 'Neutral', 'Untergriff'],
  }),
  defineStandardExercise({
    id: 'pull-up',
    name: 'Klimmzug',
    primaryMuscles: ['Latissimus'],
    secondaryMuscles: ['Bizeps', 'Mittlerer Rücken'],
    equipment: ['Klimmzugstange'],
    unit: 'reps',
    description: 'Aus dem freien Hang die Brust zur Stange ziehen und kontrolliert absenken.',
    supportsBodyweightModes: true,
  }),
  defineStandardExercise({
    id: 't-bar-row',
    name: 'T-Bar-Rudern',
    primaryMuscles: ['Mittlerer Rücken', 'Latissimus'],
    secondaryMuscles: ['Bizeps', 'Hintere Schulter'],
    equipment: ['T-Bar', 'Hantelscheiben'],
    description: 'Den T-Bar-Griff mit stabilem Oberkörper zum unteren Brustkorb ziehen.',
  }),
  defineStandardExercise({
    id: 'seated-cable-row',
    name: 'Sitzendes Kabelrudern',
    primaryMuscles: ['Mittlerer Rücken', 'Latissimus'],
    secondaryMuscles: ['Bizeps', 'Hintere Schulter'],
    equipment: ['Kabelzug', 'Ruderbank'],
    description: 'Den Griff im Sitzen zum Bauch ziehen und die Schulterblätter zusammenführen.',
    gripOptions: ['Enger Parallelgriff', 'Breit', 'Neutral', 'Einarmig'],
  }),
  defineStandardExercise({
    id: 'chest-supported-row',
    name: 'Brustgestütztes Rudern',
    primaryMuscles: ['Mittlerer Rücken'],
    secondaryMuscles: ['Latissimus', 'Bizeps', 'Hintere Schulter'],
    equipment: ['Schrägbank', 'Kurzhanteln'],
    description: 'Mit aufliegender Brust die Kurzhanteln seitlich zum Rumpf rudern.',
  }),
  defineStandardExercise({
    id: 'barbell-row',
    name: 'Langhantelrudern',
    primaryMuscles: ['Mittlerer Rücken', 'Latissimus'],
    secondaryMuscles: ['Bizeps', 'Rückenstrecker'],
    equipment: ['Langhantel'],
    description: 'Aus der Hüftbeuge die Langhantel zum Bauch ziehen und kontrolliert absenken.',
  }),
  defineStandardExercise({
    id: 'one-arm-dumbbell-row',
    name: 'Einarmiges Kurzhantelrudern',
    primaryMuscles: ['Latissimus'],
    secondaryMuscles: ['Bizeps', 'Mittlerer Rücken'],
    equipment: ['Kurzhantel', 'Flachbank'],
    description: 'Mit einer Hand abgestützt die Kurzhantel eng zur Hüfte rudern.',
  }),
  defineStandardExercise({
    id: 'straight-arm-pulldown',
    name: 'Latziehen mit gestreckten Armen',
    primaryMuscles: ['Latissimus'],
    secondaryMuscles: ['Trizeps', 'Rumpf'],
    equipment: ['Kabelzug', 'Gerade Stange'],
    description: 'Die fast gestreckten Arme aus Schulterhöhe bogenförmig zu den Oberschenkeln ziehen.',
  }),
  defineStandardExercise({
    id: 'face-pull',
    name: 'Face Pull',
    primaryMuscles: ['Hintere Schulter'],
    secondaryMuscles: ['Mittlerer Rücken', 'Rotatorenmanschette'],
    equipment: ['Kabelzug', 'Seilgriff'],
    description: 'Das Seil auf Gesichtshöhe ziehen und die Hände neben den Kopf führen.',
  }),
  defineStandardExercise({
    id: 'back-squat',
    name: 'Kniebeuge mit Langhantel',
    primaryMuscles: ['Quadrizeps', 'Gesäß'],
    secondaryMuscles: ['Beinbeuger', 'Rumpf'],
    equipment: ['Langhantel', 'Kniebeugenständer'],
    description: 'Mit der Hantel auf dem oberen Rücken tief beugen und über den Mittelfuß aufstehen.',
  }),
  defineStandardExercise({
    id: 'leg-press',
    name: 'Beinpresse',
    primaryMuscles: ['Quadrizeps', 'Gesäß'],
    secondaryMuscles: ['Beinbeuger', 'Waden'],
    equipment: ['Beinpresse'],
    description: 'Die Plattform aus gebeugten Knien wegdrücken, ohne die Knie zu überstrecken.',
  }),
  defineStandardExercise({
    id: 'romanian-deadlift',
    name: 'Rumänisches Kreuzheben',
    primaryMuscles: ['Beinbeuger', 'Gesäß'],
    secondaryMuscles: ['Rückenstrecker', 'Unterarme'],
    equipment: ['Langhantel'],
    description: 'Die Hantel mit zurückgeschobener Hüfte nah an den Beinen absenken und aufrichten.',
  }),
  defineStandardExercise({
    id: 'conventional-deadlift',
    name: 'Klassisches Kreuzheben',
    primaryMuscles: ['Gesäß', 'Rückenstrecker'],
    secondaryMuscles: ['Quadrizeps', 'Beinbeuger', 'Unterarme'],
    equipment: ['Langhantel', 'Hantelscheiben'],
    description: 'Die Hantel vom Boden mit stabilem Rücken bis zum aufrechten Stand heben.',
  }),
  defineStandardExercise({
    id: 'hack-squat',
    name: 'Hackenschmidt-Kniebeuge',
    primaryMuscles: ['Quadrizeps'],
    secondaryMuscles: ['Gesäß', 'Beinbeuger'],
    equipment: ['Hackenschmidt-Maschine'],
    description: 'Den Schlitten aus tiefer Kniebeuge entlang der Führung nach oben drücken.',
  }),
  defineStandardExercise({
    id: 'bulgarian-split-squat',
    name: 'Bulgarische Kniebeuge',
    primaryMuscles: ['Quadrizeps', 'Gesäß'],
    secondaryMuscles: ['Beinbeuger', 'Rumpf'],
    equipment: ['Kurzhanteln', 'Flachbank'],
    description: 'Mit erhöhtem hinteren Fuß das vordere Knie beugen und einbeinig aufstehen.',
  }),
  defineStandardExercise({
    id: 'walking-lunge',
    name: 'Gehende Ausfallschritte',
    primaryMuscles: ['Quadrizeps', 'Gesäß'],
    secondaryMuscles: ['Beinbeuger', 'Waden'],
    equipment: ['Kurzhanteln'],
    description: 'Abwechselnd weit nach vorn steigen, das hintere Knie senken und weitergehen.',
  }),
  defineStandardExercise({
    id: 'leg-extension',
    name: 'Beinstrecker',
    primaryMuscles: ['Quadrizeps'],
    secondaryMuscles: ['Hüftbeuger'],
    equipment: ['Beinstrecker-Maschine'],
    description: 'Das Schienbeinpolster aus gebeugten Knien bis fast zur Streckung anheben.',
  }),
  defineStandardExercise({
    id: 'seated-leg-curl',
    name: 'Sitzender Beinbeuger',
    primaryMuscles: ['Beinbeuger'],
    secondaryMuscles: ['Waden'],
    equipment: ['Sitzende Beinbeuger-Maschine'],
    description: 'Das Rollenpolster im Sitzen unter den Sitz ziehen und langsam zurückführen.',
  }),
  defineStandardExercise({
    id: 'lying-leg-curl',
    name: 'Liegender Beinbeuger',
    primaryMuscles: ['Beinbeuger'],
    secondaryMuscles: ['Waden'],
    equipment: ['Liegende Beinbeuger-Maschine'],
    description: 'In Bauchlage die Fersen gegen das Rollenpolster zum Gesäß ziehen.',
  }),
  defineStandardExercise({
    id: 'hip-thrust',
    name: 'Hip Thrust',
    primaryMuscles: ['Gesäß'],
    secondaryMuscles: ['Beinbeuger', 'Quadrizeps'],
    equipment: ['Langhantel', 'Flachbank'],
    description: 'Mit den Schulterblättern an der Bank die belastete Hüfte bis zur Streckung anheben.',
  }),
  defineStandardExercise({
    id: 'standing-calf-raise',
    name: 'Wadenheben stehend',
    primaryMuscles: ['Waden'],
    secondaryMuscles: ['Fußmuskulatur'],
    equipment: ['Wadenhebe-Maschine'],
    description: 'Unter den Schulterpolstern die Fersen kontrolliert anheben und tief absenken.',
  }),
  defineStandardExercise({
    id: 'seated-calf-raise',
    name: 'Wadenheben sitzend',
    primaryMuscles: ['Waden'],
    secondaryMuscles: ['Fußmuskulatur'],
    equipment: ['Sitzende Wadenhebe-Maschine'],
    description: 'Mit dem Kniepolster belastet die Fersen im Sitzen heben und senken.',
  }),
  defineStandardExercise({
    id: 'machine-shoulder-press',
    name: 'Schulterdrücken an der Maschine',
    primaryMuscles: ['Schultern'],
    secondaryMuscles: ['Trizeps', 'Obere Brust'],
    equipment: ['Schulterpresse'],
    description: 'Die Maschinengriffe aus Schulterhöhe nach oben drücken und kontrolliert absenken.',
  }),
  defineStandardExercise({
    id: 'dumbbell-shoulder-press',
    name: 'Kurzhantel-Schulterdrücken',
    primaryMuscles: ['Schultern'],
    secondaryMuscles: ['Trizeps', 'Obere Brust'],
    equipment: ['Kurzhanteln', 'Sitzbank'],
    description: 'Kurzhanteln von Schulterhöhe stabil über den Kopf drücken.',
  }),
  defineStandardExercise({
    id: 'dumbbell-lateral-raise',
    name: 'Seitheben mit Kurzhanteln',
    primaryMuscles: ['Seitliche Schulter'],
    secondaryMuscles: ['Trapezmuskel'],
    equipment: ['Kurzhanteln'],
    description: 'Die Kurzhanteln mit leicht gebeugten Armen seitlich bis Schulterhöhe anheben.',
  }),
  defineStandardExercise({
    id: 'cable-lateral-raise',
    name: 'Seitheben am Kabel',
    primaryMuscles: ['Seitliche Schulter'],
    secondaryMuscles: ['Trapezmuskel'],
    equipment: ['Kabelzug', 'Einhandgriff'],
    description: 'Den tiefen Kabelgriff seitlich vom Körper bis zur Schulterhöhe anheben.',
  }),
  defineStandardExercise({
    id: 'reverse-pec-deck',
    name: 'Reverse Butterfly',
    primaryMuscles: ['Hintere Schulter'],
    secondaryMuscles: ['Mittlerer Rücken', 'Trapezmuskel'],
    equipment: ['Reverse-Pec-Deck-Maschine'],
    description: 'Mit der Brust am Polster die Griffe bogenförmig nach hinten öffnen.',
  }),
  defineStandardExercise({
    id: 'rear-delt-cable-fly',
    name: 'Reverse Kabel-Flys',
    primaryMuscles: ['Hintere Schulter'],
    secondaryMuscles: ['Mittlerer Rücken', 'Trapezmuskel'],
    equipment: ['Kabelzug', 'Einhandgriffe'],
    description: 'Überkreuzte Kabel mit fast gestreckten Armen auf Schulterhöhe auseinanderziehen.',
  }),
  defineStandardExercise({
    id: 'front-raise',
    name: 'Frontheben',
    primaryMuscles: ['Vordere Schulter'],
    secondaryMuscles: ['Obere Brust', 'Trapezmuskel'],
    equipment: ['Kurzhanteln'],
    description: 'Die Kurzhanteln vor dem Körper kontrolliert bis Schulterhöhe anheben.',
  }),
  defineStandardExercise({
    id: 'barbell-curl',
    name: 'Langhantel-Curl',
    primaryMuscles: ['Bizeps'],
    secondaryMuscles: ['Unterarme'],
    equipment: ['Langhantel'],
    description: 'Die Langhantel bei ruhigen Oberarmen zur Brust beugen und langsam absenken.',
  }),
  defineStandardExercise({
    id: 'dumbbell-curl',
    name: 'Kurzhantel-Curl',
    primaryMuscles: ['Bizeps'],
    secondaryMuscles: ['Unterarme'],
    equipment: ['Kurzhanteln'],
    description: 'Die Kurzhanteln abwechselnd mit stabilen Oberarmen nach oben beugen.',
  }),
  defineStandardExercise({
    id: 'hammer-curl',
    name: 'Hammer-Curl',
    primaryMuscles: ['Brachialis', 'Bizeps'],
    secondaryMuscles: ['Unterarme'],
    equipment: ['Kurzhanteln'],
    description: 'Kurzhanteln im neutralen Griff mit ruhigen Oberarmen nach oben beugen.',
  }),
  defineStandardExercise({
    id: 'preacher-curl',
    name: 'Scott-Curl',
    primaryMuscles: ['Bizeps'],
    secondaryMuscles: ['Unterarme'],
    equipment: ['Scott-Bank', 'SZ-Stange'],
    description: 'Die Oberarme am Polster fixieren und die Stange kontrolliert beugen.',
  }),
  defineStandardExercise({
    id: 'cable-curl',
    name: 'Kabel-Curl',
    primaryMuscles: ['Bizeps'],
    secondaryMuscles: ['Unterarme'],
    equipment: ['Kabelzug', 'Gerade Stange'],
    description: 'Die Kabelstange mit angelegten Oberarmen bis vor die Brust ziehen.',
  }),
  defineStandardExercise({
    id: 'rope-pushdown',
    name: 'Trizepsdrücken am Seil',
    primaryMuscles: ['Trizeps'],
    secondaryMuscles: ['Unterarme'],
    equipment: ['Kabelzug', 'Seilgriff'],
    description: 'Das Seil bei fixierten Oberarmen nach unten drücken und unten spreizen.',
  }),
  defineStandardExercise({
    id: 'katana-triceps-extension',
    name: 'Katana-Trizepsstrecken',
    primaryMuscles: ['Trizeps'],
    secondaryMuscles: ['Schultern'],
    equipment: ['Kabelzug', 'Einhandgriff'],
    description: 'Den diagonal geführten Kabelgriff neben dem Kopf nach oben außen strecken.',
  }),
  defineStandardExercise({
    id: 'overhead-cable-triceps-extension',
    name: 'Überkopf-Trizepsstrecken am Kabel',
    primaryMuscles: ['Trizeps'],
    secondaryMuscles: ['Schultern', 'Rumpf'],
    equipment: ['Kabelzug', 'Seilgriff'],
    description: 'Das Seil aus gebeugten Ellbogen über dem Kopf nach vorn strecken.',
  }),
  defineStandardExercise({
    id: 'dip',
    name: 'Dip',
    primaryMuscles: ['Trizeps', 'Brust'],
    secondaryMuscles: ['Vordere Schulter'],
    equipment: ['Dip-Barren'],
    unit: 'reps',
    description: 'Zwischen den Holmen den Körper kontrolliert absenken und wieder hochdrücken.',
    supportsBodyweightModes: true,
  }),
  defineStandardExercise({
    id: 'machine-crunch',
    name: 'Crunch an der Maschine',
    primaryMuscles: ['Gerader Bauchmuskel'],
    secondaryMuscles: ['Seitliche Bauchmuskeln'],
    equipment: ['Crunch-Maschine'],
    description: 'Brustkorb und Becken gegen den Widerstand kontrolliert aufeinander zu bewegen.',
  }),
  defineStandardExercise({
    id: 'cable-crunch',
    name: 'Kabel-Crunch',
    primaryMuscles: ['Gerader Bauchmuskel'],
    secondaryMuscles: ['Seitliche Bauchmuskeln'],
    equipment: ['Kabelzug', 'Seilgriff'],
    description: 'Im Kniestand den Brustkorb mit dem Seil in Richtung Becken einrollen.',
  }),
  defineStandardExercise({
    id: 'hanging-leg-raise',
    name: 'Hängendes Beinheben',
    primaryMuscles: ['Gerader Bauchmuskel', 'Hüftbeuger'],
    secondaryMuscles: ['Unterarme'],
    equipment: ['Klimmzugstange'],
    unit: 'reps',
    description: 'Aus dem Hang die gestreckten oder gebeugten Beine kontrolliert nach vorn anheben.',
  }),
  defineStandardExercise({
    id: 'plank',
    name: 'Unterarmstütz',
    primaryMuscles: ['Rumpf'],
    secondaryMuscles: ['Gesäß', 'Schultern'],
    equipment: ['Trainingsmatte'],
    unit: 'seconds',
    description: 'Den Körper auf Unterarmen und Zehen in einer stabilen geraden Linie halten.',
  }),
]

export const exerciseById = new Map(
  STANDARD_EXERCISES.map((exercise) => [exercise.id, exercise]),
)

export function getExerciseDefinition(id: string): ExerciseDefinition | undefined {
  return exerciseById.get(id)
}
